baseURL = "https://AiLeil.github.io/"
languageCode = "en"
title = "AiLeil"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[params]
math = true
defaultTheme = "auto"
ShowReadingTime = true

  [params.profileMode]
  enabled = true
  title = "AiLeil"
  subtitle = "24, still a student"
  bio = "UWaterloo BMath -> UniMelb MIT"

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects/"

    [[params.profileMode.buttons]]
    name = "Essays (CN)"
    url = "/essays/"

    [[params.profileMode.buttons]]
    name = "GitHub"
    url = "https://github.com/AiLeil"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/AiLeil"

  [[params.socialIcons]]
  name = "email"
  url = "zlh4sg@gmail.com"

[menu]

  [[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 10

  [[menu.main]]
  identifier = "essays"
  name = "Essays (CN)"
  url = "/essays/"
  weight = 20

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 30
